### ISSUE TITLE
The Repository structure is not as required

### ISSUE THREAD

**Issue by pushpdeep** [communication17/Project#1]
Please refer this structure here and correct it ASAP.

the repository structure -
http://vlabs.iitb.ac.in/gitlab/Community-Docs/New-Lab-development/Round-templates

Documentation on porting of the experiment -
https://docs.google.com/document/d/1y8M1qslLjtyHmGnjclJQVEscNnB2n2JJTpeIADiuSkk/edit?usp=sharing
@communication17

**Comment by communication17** [comment]
issue resolved

**Comment by communication17** [comment]
check it now, the repository structure is as it is required

**Comment by communication17** [comment]
> Please refer this structure here and correct it ASAP.
> 
> the repository structure -
> http://vlabs.iitb.ac.in/gitlab/Community-Docs/New-Lab-development/Round-templates
> 
> Documentation on porting of the experiment -
> https://docs.google.com/document/d/1y8M1qslLjtyHmGnjclJQVEscNnB2n2JJTpeIADiuSkk/edit?usp=sharing
> @communication17

issue resolved

**Comment by communication17** [comment]
> > Please refer this structure here and correct it ASAP.
> > the repository structure -
> > http://vlabs.iitb.ac.in/gitlab/Community-Docs/New-Lab-development/Round-templates
> > Documentation on porting of the experiment -
> > https://docs.google.com/document/d/1y8M1qslLjtyHmGnjclJQVEscNnB2n2JJTpeIADiuSkk/edit?usp=sharing
> > @communication17
> 
> issue resolved

sir i made some changes now the repo structure same as it required

**Comment by pushpdeep** [comment]
@communication17 Follow the rpeo on vlabs.iitb.ac.in/gitlab/ this repo is not to be used.
